# --- !Ups
CREATE TABLE AppUser (
                    id_app_user bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
                    first_name text NOT NULL,
                    last_name text NOT NULL,
                    email text DEFAULT Null,
                    phone_number text DEFAULT Null,
                    salary numeric(20,2) DEFAULT Null,
                    is_manager boolean NOT NULL DEFAULT FALSE,
                    timestamp_created timestamp NOT NULL,
                    timestamp_edited timestamp NOT NULL,
                    CONSTRAINT AppUser_pk PRIMARY KEY (id_app_user)
);


CREATE TABLE Project (
                    id_project bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
                    name text NOT NULL,
                    description text DEFAULT Null,
                    timestamp_created timestamp NOT NULL,
                    timestamp_edited timestamp NOT NULL,
                    billable boolean NOT NULL DEFAULT TRUE,
                    owned_by bigint NOT NULL,
                    created_by bigint NOT NULL,
                    last_edited_by bigint NOT NULL,
                    id_client_Client bigint NOT NULL,
                    CONSTRAINT Project_pk PRIMARY KEY (id_project)

);

CREATE TABLE many_Projects_have_many_AppUsers (
                                                id_project_Project bigint NOT NULL,
                                                id_app_user_AppUser bigint NOT NULL,
                                                CONSTRAINT many_Projects_have_many_AppUsers_pk
                                                    PRIMARY KEY (id_project_Project,
                                                                 id_app_user_AppUser)
);

ALTER TABLE many_Projects_have_many_AppUsers
    ADD CONSTRAINT Project_fk FOREIGN KEY (id_project_Project)
    REFERENCES Project (id_project)
    ON DELETE RESTRICT ON UPDATE CASCADE;


ALTER TABLE many_Projects_have_many_AppUsers ADD CONSTRAINT AppUser_fk FOREIGN KEY (id_app_user_AppUser)
    REFERENCES AppUser (id_app_user)
    ON DELETE RESTRICT ON UPDATE CASCADE;


CREATE TABLE Client (
                    id_client bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
                    name text,
                    email text,
                    timestamp_created timestamp,
                    timestamp_edited timestamp,
                    CONSTRAINT Client_pk PRIMARY KEY (id_client)
);

ALTER TABLE Project ADD CONSTRAINT Client_fk FOREIGN KEY (id_client_Client)
    REFERENCES Client (id_client)
    ON DELETE RESTRICT ON UPDATE CASCADE;


ALTER TABLE Project ADD CONSTRAINT owned_by_reference FOREIGN KEY (owned_by)
    REFERENCES AppUser (id_app_user)
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Project ADD CONSTRAINT created_by_reference FOREIGN KEY (created_by)
    REFERENCES AppUser (id_app_user)
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Project ADD CONSTRAINT last_edited_by_reference FOREIGN KEY (last_edited_by)
    REFERENCES AppUser (id_app_user)
    ON DELETE RESTRICT ON UPDATE CASCADE;

INSERT INTO AppUser (first_name,
                    last_name,
                    is_manager,
                    timestamp_created,
                    timestamp_edited)
 VALUES ('Eka', 'E_sukunimi', TRUE, '2004-10-19 10:23:54', '2004-10-19 10:23:54'),
        ('Toka', 'T_sukunimi', TRUE, '2004-10-20 11:30:45', '2012-11-19 16:27:01');

INSERT INTO Client (name,
                    email,
                    timestamp_created,
                    timestamp_edited)
    VALUES ('Esimerkkiasiakas',
            'asiakas@yritys.fi',
            '2004-10-20 11:30:45',
            '2012-11-19 16:27:01');

INSERT INTO Project (name,
                     description,
                     timestamp_created,
                     timestamp_edited,
                     billable,
                     owned_by,
                     created_by,
                     last_edited_by,
                     id_client_Client)
    VALUES ('Testi_projekti',
            'Testi-projektin kuvaus',
            '2004-10-19 10:23:54',
            '2004-10-19 10:23:54',
            TRUE,
            1,
            2,
            2,
            1);
# --- !Downs
ALTER TABLE many_Projects_have_many_AppUsers DROP CONSTRAINT IF EXISTS Project_fk;
ALTER TABLE many_Projects_have_many_AppUsers DROP CONSTRAINT IF EXISTS User_fk;
DROP TABLE IF EXISTS many_Projects_have_many_AppUsers;
ALTER TABLE Project DROP CONSTRAINT IF EXISTS Client_fk;
ALTER TABLE Project DROP CONSTRAINT IF EXISTS owned_by_reference;
ALTER TABLE Project DROP CONSTRAINT IF EXISTS created_by_reference;
ALTER TABLE Project DROP CONSTRAINT IF EXISTS last_edited_by_reference;
DROP TABLE IF EXISTS Project;
DROP TABLE IF EXISTS AppUser CASCADE;
DROP TABLE IF EXISTS Client CASCADE;
